export const citi = [
    {
      cityName: "Hanoi",
      districts: ["Ba Dinh", "Hoan Kiem", "Dong Da"],
      wards: {
        "Ba Dinh": ["Phuc Xa", "Quan Thanh"],
        "Hoan Kiem": ["Phuc Tan", "Hang Bac"],
        "Dong Da": ["Quoc Tu Giam", "Cat Linh"],
      },
      hotels: {
        "Phuc Xa": ["Hotel A", "Hotel B"],
        "Quan Thanh": ["Hotel C", "Hotel D"],
        "Phuc Tan": ["Hotel E", "Hotel F"],
        "Hang Bac": ["Hotel G", "Hotel H"],
        "Quoc Tu Giam": ["Hotel I", "Hotel J"],
        "Cat Linh": ["Hotel K", "Hotel L"],
      },
      roomTypes: ["Single", "Double", "Suite"],
    },
    {
      cityName: "HoChiMinh",
      districts: ["District 1", "District 2", "District 3"],
      wards: {
        "District 1": ["Ward A", "Ward B"],
        "District 2": ["Ward C", "Ward D"],
        "District 3": ["Ward E", "Ward F"],
      },
      hotels: {
        "Ward A": ["Hotel X", "Hotel Y"],
        "Ward B": ["Hotel Z", "Hotel W"],
        "Ward C": ["Hotel P", "Hotel Q"],
        "Ward D": ["Hotel R", "Hotel S"],
        "Ward E": ["Hotel M", "Hotel N"],
        "Ward F": ["Hotel U", "Hotel V"],
      },
      roomTypes: ["Standard", "Deluxe", "Superior"],
    },
  ];
  
// export const citi = [
//     "Choose Destination ",
//     "Hà Nội",
//     "Hồ Chí Minh",
//     "Hải Phòng",
//     "Đà Nẵng",
//     "Cần Thơ",
//     "Hải Dương",
//     "Bắc Ninh",
//     "Hà Nam",
//     "Nam Định",
//     "Ninh Bình",
//     "Thái Bình",
//     "Thanh Hóa",
//     "Nghệ An",
//     "Hà Tĩnh",
//     "Quảng Bình",
//     "Quảng Trị",
//     "Thừa Thiên-Huế",
//     "Quảng Nam",
//     "Quảng Ngãi",
//     "Bình Định",
//     "Phú Yên",
//     "Khánh Hòa",
//     "Ninh Thuận",
//     "Bình Thuận",
//     "Kon Tum",
//     "Gia Lai",
//     "Đắk Lắk",
//     "Đắk Nông",
//     "Lâm Đồng",
//     "Bình Phước",
//     "Tây Ninh",
//     "Bình Dương",
//     "Đồng Nai",
//     "Bà Rịa-Vũng Tàu",
//     "Long An",
//     "Tiền Giang",
//     "Bến Tre",
//     "Trà Vinh",
//     "Vĩnh Long",
//     "Đồng Tháp",
//     "An Giang",
//     "Kiên Giang",
//     "Hậu Giang",
//     "Sóc Trăng",
//     "Bạc Liêu",
//     "Cà Mau",
//     "Tuyên Quang",
//     "Lào Cai",
//     "Điện Biên",
//     "Lai Châu",
//     "Sơn La",
//     "Yên Bái",
//     "Hòa Bình",
//     "Tuyên Quang",
//     "Lạng Sơn",
//     "Bắc Cạn",
//     "Quảng Ninh",
//     "Bắc Giang",
//     "Cao Bằng",
//     "Lào Cai",
//     "Hà Giang",
//     "Điện Biên",
//   ];
